# Generated by Django 4.2.1 on 2023-06-07 12:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='container',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('e', 'Enabled'), ('d', 'Disabled')], default='d', max_length=1)),
                ('expdate', models.DateTimeField(default=datetime.datetime(2023, 6, 7, 12, 10, 7, 445651))),
                ('link', models.TextField(blank=True, default=None, max_length=350, null=True)),
                ('port', models.IntegerField(blank=True, null=True, unique=True)),
                ('userid', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
